#Download base image ubuntu 18.04
FROM ubuntu:18.04

# Install GCC and G++ and make
RUN apt-get update && \
    apt-get install -y build-essential manpages-dev && \
    gcc --version

RUN mkdir -p /app/ubuntu
WORKDIR /app/ubuntu