export const BaseListJob = [
    {
        id: 1,
        position: 'tester',
        title: 'Tester for new project',
        description: 'This is main tester for project of mobile',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 2,
        position: 'tester',
        title: 'Tester for new project',
        description: 'This is main tester for project of mobile',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 3,
        position: 'tester',
        title: 'Tester for new project and developer',
        description: 'This is main tester for project of mobile',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'TP.HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 4,
        position: 'tester',
        title: 'Tester for new project',
        description: 'This is main tester for project of mobile',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'Hà Nội',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'ReactJs',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 5,
        position: 'tester',
        title: 'Tester for new project',
        description: 'This is main tester for project of mobile',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'TP.HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 6,
        position: 'tester',
        title: 'Tester for new project',
        description: 'This is main tester for project of mobile',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'TP.HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 7,
        position: 'tester',
        title: 'Tester for new project 1',
        description: 'This is main tester for project of mobile 1',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'TP.HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 8,
        position: 'tester',
        title: 'Tran Hoang Long',
        description: 'This is main tester for project of mobile 1',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'TP.HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 9,
        position: 'tester',
        title: 'Tran Hoang Long',
        description: 'This is main tester for project of mobile 1',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'TP.Đà Nẵng',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'VueJS',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
];

export const NewListJob = [
    {
        id: 1,
        position: 'tester',
        title: 'Tester for new project',
        description: 'This is main tester for project of mobile',
        coopName: 'SPKT',
        salary: '3000 - up to 5000',
        address: 'HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 2,
        position: 'tester',
        title: 'Tester for new project',
        description: 'This is main tester for project of mobile',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
    {
        id: 3,
        position: 'tester',
        title: 'Tester for new project',
        description: 'This is main tester for project of mobile',
        coopName: 'SPKT',
        salary: 'optional',
        address: 'HCM',
        listLang: ['java', 'python'],
        category: 'fulltime',
        numberApply: 5,
        startDate: (new Date()).getTime(),
        endDate: (new Date()).getTime(),
        createDate: (new Date()).getTime(),
        major: 'IT',
        listIntershipId: [1, 2, 3, 4, 5],
        deleteFlag: false
    },
]

export const TopCoop = [
    {
        id: 1,
        name: 'ABC'
    },
    {
        id: 2,
        name: 'ABC'
    },
    {
        id: 3,
        name: 'ABC'
    },
    {
        id: 4,
        name: 'ABC'
    },
    {
        id: 5,
        name: 'ABC'
    },
    {
        id: 5,
        name: 'ABC'
    },
]